### ISSUE TITLE
加载插件时出错，运行命令时出错

### ISSUE THREAD

**Issue by RepentStar** [MoBoxMC/MoBoxHunter#4]
服务器版本：spigot-1.16.5
插件列表：
EssentialsX-2.19.7.jar
GSit-1.2.2.jar
LuckPerms-Bukkit-5.4.41 .jar
MoBoxHunter.jar
PlugManX.jar
ProtocolLib.jar
SkinsRestorer.jar
spark-1.9.33-bukkit.jar
SwingThroughGrass.jar
所用jdk：oracle jdk11.0.14
使用本仓库最新release插件

关于启动插件时的报错如下：
`
[15:09:30] [Server thread/INFO]: [MoBoxHunter] Enabling MoBoxHunter v1.0-SNAPSHOT
[15:09:30] [Server thread/ERROR]: Error occurred while enabling MoBoxHunter v1.0-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: org/mossmc/mosscg/MoBoxCore/Info/InfoGroupBackend
	at org.mossmc.mosscg.MoBoxHunter.Main.onEnable(Main.java:45) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:554) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: org.mossmc.mosscg.MoBoxCore.Info.InfoGroupBackend
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:140) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 11 more
`
运行命令时报错如下：
`
[15:10:38] [Server thread/WARN]: Unexpected exception while parsing console command "moboxhunter list"
org.bukkit.command.CommandException: Unhandled exception executing command 'moboxhunter' in plugin MoBoxHunter v1.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:761) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:746) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:426) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:395) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1127) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:966) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: org/mossmc/mosscg/MoBoxCore/Game/GameBasicInfo
	at org.mossmc.mosscg.MoBoxHunter.Main.onCommand(Main.java:148) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	... 9 more
Caused by: java.lang.ClassNotFoundException: org.mossmc.mosscg.MoBoxCore.Game.GameBasicInfo
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:140) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at org.mossmc.mosscg.MoBoxHunter.Main.onCommand(Main.java:148) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	... 9 more
`

**Comment by MossCG** [comment]
你没装MoBoxCore前置
